from godot import exposed, export
from godot import *


@exposed
class TrafficLightArea(Node):
	def _ready(self):
		#Links the TLA script to the correct traffic light
		self.get_node('TrafficLightArea1').traffic_light = 'trafficlight1'
		self.get_node('TrafficLightArea2').traffic_light = 'trafficlight2'
		self.get_node('TrafficLightArea3').traffic_light = 'trafficlight3'
		self.get_node('TrafficLightArea4').traffic_light = 'trafficlight4'
		self.get_node('TrafficLightArea5').traffic_light = 'trafficlight5'
		self.get_node('TrafficLightArea6').traffic_light = 'trafficlight6'
		self.get_node('TrafficLightArea7').traffic_light = 'trafficlight7'
		self.get_node('TrafficLightArea8').traffic_light = 'trafficlight8'
		self.get_node('TrafficLightArea9').traffic_light = 'trafficlight9'
		self.get_node('TrafficLightArea10').traffic_light = 'trafficlight10'
		self.get_node('TrafficLightArea11').traffic_light = 'trafficlight11'
		self.get_node('TrafficLightArea12').traffic_light = 'trafficlight12'
		self.get_node('TrafficLightArea13').traffic_light = 'trafficlight13'
		self.get_node('TrafficLightArea14').traffic_light = 'trafficlight14'
		self.get_node('TrafficLightArea15').traffic_light = 'trafficlight15'
		self.get_node('TrafficLightArea16').traffic_light = 'trafficlight16'
		self.get_node('TrafficLightArea17').traffic_light = 'trafficlight17'
		self.get_node('TrafficLightArea18').traffic_light = 'trafficlight18'
		self.get_node('TrafficLightArea19').traffic_light = 'trafficlight19'
		self.get_node('TrafficLightArea20').traffic_light = 'trafficlight20'
		self.get_node('TrafficLightArea21').traffic_light = 'trafficlight21a'
		self.get_node('TrafficLightArea22').traffic_light = 'trafficlight22a'
		self.get_node('TrafficLightArea23').traffic_light = 'trafficlight23a'
		self.get_node('TrafficLightArea24').traffic_light = 'trafficlight24a'
		self.get_node('TrafficLightArea25').traffic_light = 'trafficlight25a'
		self.get_node('TrafficLightArea26').traffic_light = 'trafficlight26a'
		self.get_node('TrafficLightArea27').traffic_light = 'trafficlight27a'
		self.get_node('TrafficLightArea28').traffic_light = 'trafficlight28a'
		self.get_node('TrafficLightArea29').traffic_light = 'trafficlight29a'
		self.get_node('TrafficLightArea30').traffic_light = 'trafficlight30'
		self.get_node('TrafficLightArea31').traffic_light = 'trafficlight31'
		self.get_node('TrafficLightArea32').traffic_light = 'trafficlight32'
		self.get_node('TrafficLightArea33a').traffic_light = 'trafficlight33a'
		self.get_node('TrafficLightArea33b').traffic_light = 'trafficlight33a'
		self.get_node('TrafficLightArea33c').traffic_light = 'trafficlight33a'
		self.get_node('TrafficLightArea33d').traffic_light = 'trafficlight33a'
		self.get_node('TrafficLightArea34').traffic_light = 'trafficlight34a'
		self.get_node('TrafficLightArea35').traffic_light = 'trafficlight35a'
